stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - scripts/preprocess.py
      - raw/train.csv
    outs:
      - data/processed/train.parquet

  train:
    cmd: python model/train.py
    deps:
      - model/train.py
      - model/dataset.py
      - data/processed/train.parquet
    params:
      - params.yaml
